version = 1

SPDX-PackageName = "Forms API"
SPDX-PackageSupplier = "Free Software Foundation Europe <https://fsfe.org/contact>"
SPDX-PackageDownloadLocation = "https://git.fsfe.org/fsfe-system-hackers/forms/"

[[annotations]]
path = "fsfe_forms/templates/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Free Software Foundation Europe <contact@fsfe.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]] # Configuration
path = "forms-fake-fsfe-cd-front/config/**"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]] # Computer-generated files
path = "Pipfile.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"